### ISSUE TITLE
Move Tor to "top 3" Self-contained Networks

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/www.privacytools.io#101]
GNUnet, Freenet or I2P may provide better anonymity, but popularity is important too.

Especially because of the

> If you are currently browsing the Clearnet and you want to access the Dark web this section is for you.

Given most popular hidden services use Tor, I suggest moving Tor to the second place, leaving I2P first. Because unlike Tor, it's only a self-contained network, **but unlike GNUnet and Freenet, it's also pretty popular**.

**Comment by privacytoolsIO** [comment]
"GNUnet, Freenet or I2P may provide better anonymity, but popularity is important too."

I agree. For now I decided to sort the networks by popularity, relying on these numbers: http://alternativeto.net/software/tor/

Tor, I2P, Freenet and GNUnet under worth mentioning.

**Comment by Shifterovich** [comment]
Awesome.
