### ISSUE TITLE
Contributing guidelines updated. Suggestions welcome on GitHub now.

### ISSUE THREAD

**Issue by privacytoolsIO** [privacytoolsIO/www.privacytools.io#62]
Before suggestions were only welcome in our [Subreddit](https://www.reddit.com/r/privacytoolsIO/) but it makes sense to accept them here as well. I don't want to force users to sign up on reddit in order to participate.

**Comment by alexbooker** [comment]
Yeah, now you bring this up I think it makes more sense to post links to GitHub issues and pull requests _to_ Reddit as opposed to the other way round.

**Comment by mitchellcash** [comment]
Good move guys, completely agree!

**Comment by albertocoronado** [comment]
Okay so, here is where I can say the HTTPS Everywhere icon needs to be updated on the website? https://www.eff.org/https-everywhere
I am new here so please, let me know!

**Comment by mitchellcash** [comment]
@albertocoronado perfect! Please see my new pull request #63, is that what you were thinking?

I'm not sure how @privacytoolsIO wants to handle it but I would opt for a new issue being opened for each new discussion, that way it is easier to track and close off and resolve open discussions on each topic separately.

**Comment by albertocoronado** [comment]
Yes! Thank you @mitchellcash 

I also agree with what you said about opening a new issue for each discussion. I would do what you did with #63 but I do not know how to do it yet, I am looking into it.
