### ISSUE TITLE
Add PureVPN to the VPN list

### ISSUE THREAD

**Issue by anonsubmitter** [privacytoolsIO/www.privacytools.io#71]
PureVPN:
- [Is based in Hong Kong](https://www.purevpn.com/contact_us.php)
- [Supports encryption](https://www.purevpn.com/features.php), [but is not enabled by default](https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa#gistcomment-1861634)
- [Accepts Bitcoin](https://www.purevpn.com/order)
- [Supports OpenVPN](https://support.purevpn.com/openvpn-manual-setup-guide)
- [Has a no logging policy](https://www.purevpn.com/privacy-policy.php)

**Comment by Shifterovich** [comment]
- [uses shared keys?](https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa)

**Comment by anonsubmitter** [comment]
[Apparently PureVPN logs timestamps and bandwidth](https://thatoneprivacysite.net/vpn-comparison-chart/).
