### ISSUE TITLE
Update to privacy related "about:config" tweaks in Firefox

### ISSUE THREAD

**Issue by anonsubmitter** [privacytoolsIO/www.privacytools.io#75]
I found these two threads about some about:config privacy enhancements that I thought might be of interest:
[https://airvpn.org/topic/19582-hardening-of-firefox/](https://airvpn.org/topic/19582-hardening-of-firefox/)
[https://airvpn.org/topic/15769-how-to-harden-firefox-extreme-edition/](https://airvpn.org/topic/15769-how-to-harden-firefox-extreme-edition/)

I especially found this part from the first link interesting:

> network.http.send.RefererHeader"
> - sends the next website that you visit information from which site you come (e.g. by clicking on a link)
>   standard-value is "2" which means it does send these informations.
>   setting the value to "1" is the same, only if you click on images, the RefererHeader won't be send anymore.
>   setting the value to "0" disables the RefererHeaders completely.

The correct entry is however `network.http.sendRefererHeader` and I did not find the entry for HTTPS pages that the poster mentioned after that, so maybe they were merged into one entry?

**Comment by Atavic** [comment]
You can load a preconfigured [user.js](https://github.com/pyllyukko/user.js) file to harden your firefox.
