### ISSUE TITLE
Consider changing ownCloud to Nextcloud

### ISSUE THREAD

**Issue by kc1212** [privacytoolsIO/www.privacytools.io#82]
ownCloud has been forked to Nextcloud, many core developers have also moved on to Nextcloud. Wikipedia has more insight and references for the history and the reason of the fork https://en.wikipedia.org/wiki/Nextcloud. 

If this issue is valid then I'm happy to make a PR to update the website.

**Comment by johnnagro** [comment]
both can probably be offered

**Comment by privacytoolsIO** [comment]
Good idea! Done
