### ISSUE TITLE
Add Umbrella App

### ISSUE THREAD

**Issue by rorymbyrne** [privacytoolsIO/www.privacytools.io#83]
Hey,

Great site and very useful for digisec trainings!

Just wanted to see can we space on the site for Umbrella App. It's free, open source on Android and contains tons of lessons on privacy related issues like digital and physical security - from how to send a secure email to dealing with being under physical surveillance.

Google Play Store:
https://play.google.com/store/apps/details?id=org.secfirst.umbrella

Amazon App Store:
https://www.amazon.com/Security-First-Umbrella-made-easy/dp/B01AKN9M1Y

F-Droid Repo:
https://secfirst.org/fdroid/repo

Github Repo:
https://github.com/securityfirst

Code Audit:
https://secfirst.org/blog.html

**Comment by johnnagro** [comment]
just for public disclosure if it wasn't obvious, @rorymbyrne is the co-founder of the for-profit training company that makes Umbrella

**Comment by rorymbyrne** [comment]
@johnnagro Yes, sorry I forgot to add that, thought it was obvious! Yes for clarity, we a registered Ltd Company in the UK as we wouldn't fit the narrow range of activities that the UK Charity Commission grants status to (essentially you need to be taking public donations in a certain band of topics). AFAIK our setup is pretty similar to how The Guardian Project or Open Whisper Systems do things in the US, we get the funds to build Umbrella as an open source tool through grants.

**Comment by privacytoolsIO** [comment]
Added. Thanks for creating an app like that.
