### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by johnnagro** [privacytoolsIO/www.privacytools.io#90]
Do you need help dealing with PR's etc? I am happy to help. Maybe the account should be migrated to an organization and you can get a few privacy advocates to help you manage the site? I'd be willing to contribute time/resources to help manage it.

Also, contribution guidelines could be fleshed out to include what you/we would consider a good tool, not just the technical constraints on logo size, etc.

**Comment by bakku** [comment]
Would also love to become part of this great site.

**Comment by Shifterovich** [comment]
I agree that the account should be turned into an organization.

**Comment by privacytoolsIO** [comment]
Thanks for offering help, guys. I've sent invites already.
